#
# Configure a default setup of Home Assistant (frontend, api, etc)
#
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named customizations
  customize_glob: !include_dir_merge_named customizations_glob
#  customize_glob: !include /customizations_glob/customize-glob.yaml

  media_dirs:
    local: /media
#
script: !include scripts.yaml
# scene: !include scenes.yaml
# switch: !include switches.yaml
command_line: !include command_line.yaml

logger:
#  default: warning
  default: info
#  logs: {}
  logs:
#    pydeconz: debug
#    homeassistant.components.deconz: d ebug
#    homeassistant.components.smartthings.light: info
#    custom_compoments_pyscripts: info
    custom_components.icloud3: debug
#    pyicloud: debug









