#
# Configure a default setup of Home Assistant (frontend, api, etc)
#
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named customizations
  customize_glob: !include_dir_merge_named customizations_glob
  media_dirs:
    local: /media

## ny struktur
template: !include_dir_merge_list entities/templates
rest: !include_dir_merge_list entities/rest
sensor: !include_dir_merge_list entities/sensors
binary_sensor: !include_dir_merge_list entities/binary_sensors
input_boolean:  !include_dir_merge_named entities/input_boolean
input_number:   !include_dir_merge_named entities/input_number
input_datetime: !include_dir_merge_named entities/input_datetime
input_select:   !include_dir_merge_named entities/input_selects
input_text:     !include_dir_merge_named entities/input_text
group: !include_dir_merge_named entities/groups


## End ny struktur
#
script: !include scripts.yaml
# scene: !include scenes.yaml
# switch: !include switches.yaml
command_line: !include command_line.yaml

logger:
  default: info
  logs:
    custom_components.icloud3: debug









