#
# Configure a default setup of Home Assistant (frontend, api, etc)
#
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named customizations
  customize_glob: !include_dir_merge_named customizations_glob
  media_dirs:
    local: /media

## ny struktur
template: !include_dir_merge_list entities/templates


## End ny struktur
#
script: !include scripts.yaml
# scene: !include scenes.yaml
# switch: !include switches.yaml
command_line: !include command_line.yaml

logger:
  default: info
  logs:
    custom_components.icloud3: debug









