esphome:
  name: olimex-bluetooth-proxy-f1ba90
  friendly_name: Bryggers ESP Bluetooth Proxy
  name_add_mac_suffix: false

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

logger:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    mode: CLK_OUT
    pin: GPIO17
  power_pin: GPIO5
  phy_addr: 0



ota:
  platform: esphome
esp32_ble_tracker:
bluetooth_proxy:
  active: true


api:
  encryption:
    key: snMuZ0Py2ZIVlIXVLvpP4EadxsFEyIuKWkb4J6Au11U=



